ListenAddress: ":4201"
SubscribePath: "/ssl-status/subscribe"
RefereeAddress: "224.5.23.1:10003"
SendingInterval: "100ms"
ServerProxy:
  Enabled: true
  Scheme: "ws"
  Address: "localhost:4202"
  Path: "/ssl-status/publish"
  User: "default"
  Password: "default"
  ReconnectInterval: "30s"